# Generated by Django 3.2.3 on 2021-06-25 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('start_bid', models.IntegerField()),
                ('category', models.CharField(choices=[('EL', 'electricity'), ('TOY', 'toy'), ('BK', 'book'), ('CL', 'clothing')], max_length=3)),
            ],
        ),
    ]
