# Generated by Django 3.2.3 on 2021-06-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_listing_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='url',
            field=models.URLField(default='null', max_length=250),
            preserve_default=False,
        ),
    ]
