# Generated by Django 3.2.3 on 2021-06-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20210626_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='C:\\Users\\pfleg\\OneDrive\\Desktop\\LifeLongLearning\\EdX\\cs50_WebProgramming\\SqlModelsMigrations\\commerce\\auctions\\images'),
        ),
    ]
