# Generated by Django 3.2.3 on 2021-07-03 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_bids_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='bidder',
        ),
        migrations.AddField(
            model_name='bids',
            name='created_by',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='auctions.user'),
            preserve_default=False,
        ),
    ]
