# Generated by Django 3.2.3 on 2021-07-06 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_listing_auction_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='posted_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posted_by', to='auctions.user'),
            preserve_default=False,
        ),
    ]
