# Generated by Django 3.2.3 on 2021-07-06 15:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_comments_posted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='watched_by',
            field=models.ManyToManyField(blank=True, related_name='watched_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
