# Generated by Django 3.2.3 on 2021-07-06 15:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_listing_watched_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='watched_by',
        ),
        migrations.AddField(
            model_name='listing',
            name='watch_list',
            field=models.ManyToManyField(blank=True, related_name='watch_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
